spring.application.name=task_service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/db_task
spring.datasource.username=postgres
spring.datasource.password=purnama1
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

smtp.host=smtp.gmail.com
smtp.port=587

server.servlet.session.timeout=60

app.file.upload-path=./uploads
spring.jackson.time-zone=Asia/Jakarta

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta