spring.application.name=gateway_service

server.port=8080

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/userSvc/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/userSvc/(?<segment>.*), /$\{segment}

# TASK SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=task-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/taskSvc/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/taskSvc/(?<segment>.*), /$\{segment}

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

max_requests=5
time_window_seconds=30